import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import{FormsModule} from '@angular/forms';
import { AppRoutingModule } from '@src/app/app-routing.module';
import { AppComponent } from '@src/app/app.component';
import {HttpClientModule} from '@angular/common/http';
import { MyweatherdetailsModule } from '@src/app/myweatherdetails/myweatherdetails.module';
import { MyweatherModule } from '@src/app/myweather/myweather.module';
import{MyweatherService} from '@src/app/myweather.service';
import { PageNotFoundComponent } from '@src/app/page-not-found/page-not-found.component';
import { AutoGeneratedComponent } from '@src/app/auto-generated/auto-generated.component';



@NgModule({
  declarations: [
    AppComponent,
    PageNotFoundComponent,
    AutoGeneratedComponent 
  ],
  imports: [
    BrowserModule,
    AppRoutingModule,
    HttpClientModule,
    FormsModule,
     MyweatherdetailsModule,
   /* MyweatherModule */
  ],


  providers: [ MyweatherService],
  bootstrap: [AppComponent],
  exports: [PageNotFoundComponent]
})
export class AppModule { }
